services:
  web:
    container_name: json-placeholder-container
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_PORT=${MONGO_INITDB_ROOT_PORT}
      - MONGO_INITDB_ROOT_HOST=${MONGO_INITDB_ROOT_HOST}
      - MONGO_INITDB_ROOT_DBNAME=${MONGO_INITDB_ROOT_DBNAME}
  db:
    image: topz2k480/json-placeholder-turbit:latest
    container_name: jsonplaceholder-mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - jsonplaceholderdata:/data/db
volumes:
  jsonplaceholderdata:
    driver: local