version: '3.8'
services:
  web:
    container_name: json-placeholder-container
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URI=${MONGO_URI}
  db:
    image: mongo
    container_name: jsonplaceholder-mongodb
    env_file:
      - .env
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - jsonplaceholderdata:/data/db
volumes:
  jsonplaceholderdata:
    driver: local